export const LEVELS = [
  {
    id: 1,
    name: '小状况来了',
    badge: '新手救场',
    timeLimit: 35,
    targetAccuracy: 100,
    incidents: [
      { id: 'spill-1', icon: '💦', title: '地上洒水了', tip: '别滑倒，快处理。', actionId: 'mop', urgency: 1 },
      { id: 'box-1', icon: '📦', title: '货架空了一格', tip: '补上就稳了。', actionId: 'restock', urgency: 1 },
      { id: 'lost-1', icon: '🧒', title: '小朋友找不到家人', tip: '广播一下。', actionId: 'broadcast', urgency: 2 },
    ],
  },
  {
    id: 2,
    name: '顾客有点急',
    badge: '稳住别慌',
    timeLimit: 32,
    targetAccuracy: 100,
    incidents: [
      { id: 'angry-2', icon: '😤', title: '顾客急了', tip: '先把情绪稳住。', actionId: 'calm', urgency: 2 },
      { id: 'spill-2', icon: '🥤', title: '饮料打翻了', tip: '地面要快点擦。', actionId: 'mop', urgency: 2 },
      { id: 'light-2', icon: '💡', title: '灯牌不亮了', tip: '修一下才显眼。', actionId: 'repair', urgency: 1 },
      { id: 'ask-2', icon: '❓', title: '有人迷路了', tip: '给 TA 指个方向。', actionId: 'guide', urgency: 1 },
    ],
  },
  {
    id: 3,
    name: '手忙脚乱',
    badge: '连环救场',
    timeLimit: 30,
    targetAccuracy: 90,
    incidents: [
      { id: 'cart-3', icon: '🛒', title: '购物车卡住了', tip: '工具上场。', actionId: 'repair', urgency: 2 },
      { id: 'shelf-3', icon: '🧃', title: '爆款断货了', tip: '马上补。', actionId: 'restock', urgency: 3 },
      { id: 'kid-3', icon: '😭', title: '小朋友哭了', tip: '广播找家人。', actionId: 'broadcast', urgency: 3 },
      { id: 'wet-3', icon: '🧊', title: '地面湿滑', tip: '先清掉危险。', actionId: 'mop', urgency: 2 },
      { id: 'queue-3', icon: '😵', title: '队伍快炸了', tip: '安抚一下。', actionId: 'calm', urgency: 2 },
    ],
  },
  {
    id: 4,
    name: '全场快炸',
    badge: '高压救援',
    timeLimit: 28,
    targetAccuracy: 90,
    incidents: [
      { id: 'alarm-4', icon: '🚨', title: '广播找人', tip: '别让人等急。', actionId: 'broadcast', urgency: 3 },
      { id: 'mess-4', icon: '🍿', title: '零食撒了一地', tip: '地面先救回来。', actionId: 'mop', urgency: 2 },
      { id: 'broken-4', icon: '🧯', title: '设备报警', tip: '工具快上。', actionId: 'repair', urgency: 3 },
      { id: 'empty-4', icon: '🥛', title: '冷柜空了', tip: '补货才有排面。', actionId: 'restock', urgency: 2 },
      { id: 'where-4', icon: '🧓', title: '阿姨找不到出口', tip: '指路最关键。', actionId: 'guide', urgency: 1 },
      { id: 'mad-4', icon: '😡', title: '顾客要爆了', tip: '先稳住人。', actionId: 'calm', urgency: 3 },
    ],
  },
  {
    id: 5,
    name: '救场王登场',
    badge: '终极救场',
    timeLimit: 26,
    targetAccuracy: 90,
    incidents: [
      { id: 'spill-5', icon: '🧃', title: '果汁飞了', tip: '拖把冲。', actionId: 'mop', urgency: 3 },
      { id: 'lost-5', icon: '👧', title: '小朋友走散', tip: '广播找人。', actionId: 'broadcast', urgency: 3 },
      { id: 'angry-5', icon: '🤯', title: '顾客破防', tip: '先安抚。', actionId: 'calm', urgency: 3 },
      { id: 'tool-5', icon: '🛠️', title: '机器罢工', tip: '维修一下。', actionId: 'repair', urgency: 3 },
      { id: 'stock-5', icon: '🍓', title: '爆款没了', tip: '马上补货。', actionId: 'restock', urgency: 3 },
      { id: 'guide-5', icon: '🗺️', title: '路线乱了', tip: '指明方向。', actionId: 'guide', urgency: 2 },
      { id: 'water-5', icon: '🧊', title: '地面打滑', tip: '快擦干。', actionId: 'mop', urgency: 2 },
    ],
  },
];
